apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: utils
  labels:
    svc: consul-svc
spec:
  type: LoadBalancer
  selector:
    svc: consul
  ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
      name: consul-web
    - port: 8600
      targetPort: 8600
      protocol: TCP
      name: consul-api
