apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
  namespace: utils
  labels:
    pvc: consul
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-node-pvc
  namespace: utils
  labels:
    pvc: consul-node
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi