apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: utils
  labels:
    svc: postgres
spec:
  selector:
    svc: postgres
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      name: postgres-nodeport
      targetPort: 5432
