apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: utils
  labels:
    svc: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      svc: postgres
  template:
    metadata:
      name: postgress
      labels:
        svc: postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:11
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username.txt
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password.txt
            - name: POSTGRES_DB
              value: groups_database
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
