apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: groups
  labels:
    svc: postgres
spec:
  selector:
    svc: postgres
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: postgres-dataport
      targetPort: 5432

