apiVersion: v1
kind: ConfigMap
metadata:
  name: utils-config
  namespace: utils
data:
  consul_config: |
    {
      "datacenter" : "central-gc",
      "data_dir" : "/consul/data",
      "log_level" : "INFO",
      "node_name" : "groups-consul",
      "server" : true,
      "telemetry" : {
        "prometheus_retention_time" : "30s"
      }
    }
  vault_config: |
    storage " consul" {
      address = "consul-svc:8500"
      path = "vault
    }

    listener "tcp" {
      address = "vault-svc:8200
      tls_disable = 1
    }

    telemetry {
      prometheus_retention_time = "30s",
      disable_hostname = true
    }
