apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: groups
  name: vault-statefulset
  labels:
    svc: vault
spec:
  serviceName: vault
  selector:
    matchLabels:
      svc: vault
  template:
    spec:
      containers:
        - name: vault-pod
          image: vault:1.2.1
          volumeMounts:
            - mountPath: /vault/logs
              name: vault_logs
            - mountPath: /vault/files
              name: vault_files
            - mountPath: /vault/config
              name: vault_config
      volumes:
        - name: vault_logs
          persistentVolumeClaim:
            claimName: vault_logs_claim
        - name: vault_files
          persistentVolumeClaim:
            claimName: vault_files_claim
        - name: vault_config
          configMap:
            name: groups-config
            items:
              - key: vault_config
                path: config.hcl
