apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-logs-claim
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-files-claim
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
