spring:
  datasource:
    username: group_admin
    password: groupsareverybusy
    url: jdbc:postgresql://localhost:5432/groups_database
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/auth/realms/search-realm
        registration:
          client-id: service-apis
          client-secret: da17d41c-68b8-44f7-b64b-07e52c7241d3
