apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-pods
  labels:
    svc: consul
  namespace: utils
spec:
  serviceName: consul
  replicas: 1
  selector:
    matchLabels:
      svc: consul
  template:
    spec:
      containers:
        - name: consul
          image: consul:1.5.3
          volumeMounts:
            - mountPath: /consul/data
              name: consul-pvc
            - mountPath: /consul/config
              name: consul-config
      volumes:
        - name: consul-pvc
          persistentVolumeClaim:
            claimName: consul-pvc
        - name: consul-config
          configMap:
            name: groups-config
            items:
              - key: consul_config
                path: config.json
