apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    name: grafana
spec:
  selector:
    matchLabels:
      name: grafana
  template:
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:6.3.2
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasource
            - mountPath: /etc/grafana
              name: grafana-config
      volumes:
        - name: grafana-datasource
          configMap:
            name: grafana-config
            items:
              - key: promethues_datasource
                path: promethues_datasource.yml
        - name: grafana-config
          configMap:
            name: grafana-config
            items:
              - key: grafana_ini
                path: grafana.ini