apiVersion: v1
kind: Service
metadata:
  name: promethus-svc
  namespace: monitoring
  labels:
    svc: prometheus-svc
spec:
  selector:
    svc: prometheus
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
      name: prometheus-web
      targetPort: 9090
