apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-service
  labels:
    svc: grafana
spec:
  selector:
    name: grafana
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana-web

