{
 "title": "Groups Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Groups Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "group_create_total" }
   ]
  },
  {
   "title": "Group Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "create_group_seconds_count" },
    { "expr": "create_group_seconds_max" },
    { "expr": "create_group_seconds_sum" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    },
    {
     "expr": "http_server_requests_seconds_sum"
    },
    {
     "expr": "http_server_requests_seconds_max"
    }
   ]
  }
 ]
}