apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: groups
  labels:
    svc: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      svc: postgres
  template:
    metadata:
      name: postgress
      labels:
        svc: postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:11
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
